---

- name: Restart Redis (Manual)
  shell: |
    pkill -f "redis-server" || true
    sleep 1
    redis-server {{ redis_conf_dir }}/redis.conf --daemonize yes
  become: yes
  become_user: "{{ redis_user }}"
  when: ansible_service_mgr != 'systemd'
