version: '3'

services:
  redis-node-1:
    image: redis-node-base:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-node-1
    hostname: redis-node-1
    networks:
      redis-net:
        ipv4_address: 10.10.0.11
    ports:
      - "2301:22"
      - "6471:6379"
    restart: always

  redis-node-2:
    image: redis-node-base:latest
    container_name: redis-node-2
    hostname: redis-node-2
    networks:
      redis-net:
        ipv4_address: 10.10.0.12
    ports:
      - "2302:22"
      - "6472:6379"
    restart: always

  redis-node-3:
    image: redis-node-base:latest
    container_name: redis-node-3
    hostname: redis-node-3
    networks:
      redis-net:
        ipv4_address: 10.10.0.13
    ports:
      - "2303:22"
      - "6473:6379"
    restart: always

  redis-node-4:
    image: redis-node-base:latest
    container_name: redis-node-4
    hostname: redis-node-4
    networks:
      redis-net:
        ipv4_address: 10.10.0.14
    ports:
      - "2304:22"
      - "6474:6379"
    restart: always

  redis-node-5:
    image: redis-node-base:latest
    container_name: redis-node-5
    hostname: redis-node-5
    networks:
      redis-net:
        ipv4_address: 10.10.0.15
    ports:
      - "2305:22"
      - "6475:6379"
    restart: always

  redis-node-6:
    image: redis-node-base:latest
    container_name: redis-node-6
    hostname: redis-node-6
    networks:
      redis-net:
        ipv4_address: 10.10.0.16
    ports:
      - "2306:22"
      - "6476:6379"
    restart: always

networks:
  redis-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
